
name: CI

on:                                 # Controls when the workflow will run
  push:                             # Triggers the workflow on push/pull request events but only for the main branch
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:                # Allows you to run this workflow manually from the Actions tab
    inputs:
      whoareyou:
        description: 'Username'
        default: 'Mr.X'
        required: true

jobs:                               # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  build:                            # This workflow contains a single job called "build"
    runs-on: ubuntu-latest          # The type of runner that the job will run on

    steps:                          # Steps represent a sequence of tasks that will be executed as part of the job
      - uses: actions/checkout@v2   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Step 1 - Prepare the build environment
        env:
          WHO_ARE_U: ${{ github.event.inputs.whoareyou }}
        run: |
          python actions/init.py ${{ github.event.inputs.whoareyou }}

      - name: Step 2 - Compile all sources    # Runs a set of commands using the runners shell
        env:
          WHO_ARE_U: ${{ github.event.inputs.whoareyou }}
        run: |
          echo Add other actions to build, test, and deploy your project.
          echo "::set-output name=$WHO_ARE_U::$(./actions/git.sh ${{ github.sha }})"
          python actions/run.py
