
name: CI

on:                                 # Controls when the workflow will run
  push:                             # Triggers the workflow on push or pull request events but only for the main branch
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:                # Allows you to run this workflow manually from the Actions tab
    inputs:
      whoareyou:
        description: 'Username'
        required: true
        default: 'Mr.X'

jobs:                               # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  build:                            # This workflow contains a single job called "build"
    runs-on: ubuntu-latest          # The type of runner that the job will run on

    steps:                          # Steps represent a sequence of tasks that will be executed as part of the job
      - uses: actions/checkout@v2   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Step 1 - Prepare the build environment
        env:
          WHOAREU: ${{ github.event.inputs.whoareyou }}
        run: |
          echo '>>> Print identification header'
          echo "$(date +'%Y-%m-%dT%H:%M:%S') *** Hello ${{ github.event.inputs.whoareyou }} (env_value: $WHOAREU)"

          echo '>>> Authenticating @ GitHub'
          echo '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' | gh auth login --with-token

          echo '>>> Fetching git diff ...'
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }}

          echo '>>> List workflows'
          gh workflow view CI


      # Runs a set of commands using the runners shell
      - name: Step 2 - Compile all sources
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          gh repo view php-savers
